---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_ROLES_PATH: ~/.cache/molecule/ansible-role-hardening/${MOLECULE_SCENARIO_NAME}/roles:${MOLECULE_PROJECT_DIRECTORY}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      almalinux9:
        kernel_lockdown: true
        manage_timesyncd: false
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
        manage_suid_sgid_permissions: false
        system_upgrade: false
      almalinux10:
        crypto_policy: DEFAULT
        kernel_lockdown: true
        manage_auditd: false
        manage_rkhunter: false
        manage_timesyncd: false
        packages_redhat:
          - audispd-plugins
          - audit
          - cracklib
          - gnupg2
          - libpwquality
          - openssh-server
          - postfix
          - psacct
          - python3-dnf-plugin-post-transaction-actions
          - rsyslog
          - rsyslog-gnutls
          - systemd-journal-remote
          - vlock
          - words
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
        manage_suid_sgid_permissions: false
        manage_ufw: false
        system_upgrade: false
platforms:
  - name: almalinux9
    box: bento/almalinux-9
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 2048
  - name: almalinux10
    box: almalinux/10-kitten-x86_64_v2
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 2048
verifier:
  name: ansible
scenario:
  name: almalinux
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
