---
collections:
  - name: ansible.posix
    version: 1.6.0
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.crypto
    version: 2.22.0
    source: https://github.com/ansible-collections/community.crypto.git
    type: git
  - name: community.general
    version: 9.4.0
    source: https://github.com/ansible-collections/community.general.git
    type: git
