---
collections:
  - name: ansible.posix
    version: 2.0.0
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.crypto
    version: 3.0.0
    source: https://github.com/ansible-collections/community.crypto.git
    type: git
  - name: community.general
    version: 11.1.0
    source: https://github.com/ansible-collections/community.general.git
    type: git
