---
- name: add motd
  become: true
  ansible.builtin.template:
    src: etc/motd.j2
    dest: /etc/motd
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - motd
    - CCE-80763-6
    - CIS-UBUNTU2004-1.7.1
    - CIS-UBUNTU2004-1.7.4

- name: add issue and issue.net
  become: true
  ansible.builtin.template:
    src: etc/issue.j2
    dest: "{{ item }}"
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  with_items:
    - /etc/issue
    - /etc/issue.net
  tags:
    - issue
    - CCE-80763-6
    - CIS-UBUNTU2004-1.7.2
    - CIS-UBUNTU2004-1.7.3
    - CIS-UBUNTU2004-1.7.5
    - CIS-UBUNTU2004-1.7.6
...
