---
- name: Ensure kmod is installed
  become: true
  ansible.builtin.package:
    name: kmod
    state: present

- name: Blacklist kernel file system modules
  become: true
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disablefs.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      {% for module in fs_modules_blocklist %}
      blacklist {{ module }}
      {% endfor %}

- name: Blacklist kernel network modules
  become: true
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disablenet.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      {% for module in net_modules_blocklist %}
      blacklist {{ module }}
      {% endfor %}

- name: Allow USB kernel modules if USBGuard is used
  ansible.builtin.set_fact:
    misc_modules_usbguard: "{{ misc_modules_blocklist | reject('search', 'usb') | list }}"

- name: Blacklist misc kernel modules
  become: true
  ansible.builtin.copy:
    dest: /etc/modprobe.d/disablemod.conf
    mode: "0644"
    owner: root
    group: root
    content: |
      {% for module in (misc_modules_usbguard if manage_usbguard else misc_modules_blocklist) %}
      blacklist {{ module }}
      {% endfor %}

- name: Stat blacklisted kernel modules
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /usr/sbin/modprobe -c | grep -o '^blacklist .*' | awk '{print $2}'
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: modprobe_blacklist.rc != 0
  register: modprobe_blacklist

- name: Block blacklisted kernel modules
  become: true
  ansible.builtin.copy:
    content: |
      # Blacklisted kernel modules - ansible managed
      {% for module in modprobe_blacklist.stdout_lines | sort | unique %}
      install {{ module }} /bin/true
      {% endfor %}
    dest: /etc/modprobe.d/blacklist-blocked.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
