---
- name: systemd system.conf
  become: 'yes'
  template:
    src: etc/systemd/system.conf.j2
    dest: /etc/systemd/system.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags:
    - systemd
    - system.conf

- name: systemd user.conf
  become: 'yes'
  template:
    src: etc/systemd/user.conf.j2
    dest: /etc/systemd/user.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  tags:
    - systemd
    - user.conf
...
