---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
  provider_options:
    linked_clone: false
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      centos:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
      centos-stream:
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
platforms:
  - name: centos
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
    box: bento/centos-8
  - name: centos-stream
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
    box: "centos-stream/20201217"
    box_url: "https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-Vagrant-8-20201217.0.x86_64.vagrant-virtualbox.box"
    box_download_checksum: "9e4d9b9dadad431b1234249e3d68bb24a03ae64dc55146751dc70760db2b5856"
    box_download_checksum_type: "sha256"
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint .
  yamllint -d "{extends: default, rules: {line-length: {level: warning}}}" .
scenario:
  name: centos
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
