---
automatic_updates:
  enabled: true
  only_security: true
  reboot: false
  reboot_from_time: "2:00"
  reboot_time_margin_mins: 1
  custom_origins: ""
disable_ipv6: true
disable_wireless: true
manage_suid_sgid_permissions: false
sshd_admin_net:
  - 0.0.0.0/0
sshd_allow_groups:
  - vagrant
  - sudo
sshd_match_users:
  - user: testuser01
    rules:
      - AllowUsers testuser01
      - AuthenticationMethods password
      - PasswordAuthentication yes
  - user: testuser02
    rules:
      - AllowUsers testuser02
      - Banner none
