---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      noble:
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
      questing:
        manage_auditd: false
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
        automatic_updates:
          enabled: true
          only_security: true
          reboot: true
          reboot_from_time: "2:00"
          reboot_time_margin_mins: 1
          custom_origins:
            - "Docker:questing"
      resolute:
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_groups:
          - vagrant
          - sudo
platforms:
  - name: noble
    box: bento/ubuntu-24.04
    config_options:
      vm.boot_timeout: 600
      ssh.key_type: ed25519
    instance_raw_config_args:
      - vbguest.auto_update = false
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--cableconnected1", "on"]
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
  - name: questing
    box: konstruktoid/ubuntu-25.10
    config_options:
      vm.boot_timeout: 600
      ssh.key_type: ed25519
    instance_raw_config_args:
      - vbguest.auto_update = false
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--cableconnected1", "on"]
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
  - name: resolute
    box: konstruktoid/ubuntu-26.04
    config_options:
      vm.boot_timeout: 600
      ssh.key_type: ed25519
    instance_raw_config_args:
      - vbguest.auto_update = false
    provider_raw_config_args:
      - customize ["modifyvm", :id, "--cableconnected1", "on"]
      - customize ['modifyvm', :id, '--uart1', '0x3F8', '4']
      - customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]
verifier:
  name: ansible
scenario:
  name: ubuntu
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
