---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      buster:
        ansible_python_interpreter: "/usr/bin/python3"
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
        system_upgrade: "no"
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3"
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
        system_upgrade: "no"
      contrib:
        ansible_python_interpreter: "/usr/bin/python3"
        sshd_admin_net: "0.0.0.0/0"
        sshd_allow_groups: "vagrant sudo"
        system_upgrade: "no"
platforms:
  - name: buster
    box: bento/debian-10
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: bullseye
    box: debian/bullseye64
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: contrib
    box: debian/contrib-testing64
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint --exclude .git --exclude .github --exclude tests/
  yamllint -d "{extends: default, ignore: .git*, rules: {line-length: {level: warning}}}" .
scenario:
  name: debian
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
