---
# https://access.redhat.com/solutions/253273
# sudo subscription-manager register --username=USER --password=PASSWORD --auto-attach
# sudo subscription-manager unregister
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
  log: true
  inventory:
    host_vars:
      redhat:
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - vagrant
          - sudo
platforms:
  - name: redhat
    box: generic/rhel8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - vbguest.auto_update = false
    memory: 1024
verifier:
  name: ansible
scenario:
  name: redhat
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
