---
ansible:
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=${MOLECULE_SCENARIO_DIRECTORY}/inventory/
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: almalinux10
    image: docker.io/almalinux:10
    command: sleep 1d
    privileged: true
    volumes:
  - name: resolute
    image: docker.io/ubuntu:resolute
    command: sleep 1d
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: trixie
    image: docker.io/debian:trixie-slim
    command: sleep 1d
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  playbooks:
    converge: "../default/converge.yml"
    verify: "../default/verify.yml"
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      interpreter_python: auto_silent
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
  log: true
  inventory:
    directory: ./inventory
verifier:
  name: ansible
scenario:
  name: docker
  create_sequence:
    - dependency
    - create
    - prepare
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
