name: Issue assignment

on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  auto-assign:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: 'auto-assign issue'
        uses: pozil/auto-assign-issue@edee9537367a8fbc625d27f9e10aa8bad47b8723 # v1.13.0
        with:
          assignees: konstruktoid
